**NUMPY ARRAY SLICING**

In [2]:
import numpy as np


In [4]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [5]:
print(arr[4:])

[5 6 7]


In [6]:
print(arr[:4])

[1 2 3 4]


In [8]:
arr=np.array([1,2,3,4,5,6,7,8,9,0])
x=arr[1:8:2]
print(x)

[2 4 6 8]


In [10]:
arr=np.array([1,2,3,4,5,6,7,8,9,0])
x=arr[-3:-1]
print(x)

[8 9]


In [11]:
arr=np.array([1,2,3,4,5,6,7,8,9,0])
x=arr[8:1:-1]
print(x)

[9 8 7 6 5 4 3]


In [12]:
arr=np.array([1,2,3,4,5,6,7,8,9,0])
x=arr[::2]
print(x)

[1 3 5 7 9]


**Slicing 2-D Array**

In [14]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr[1,1:4])

[7 8 9]


In [15]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr[0:2,2])

[3 8]


In [16]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


**NUMPY ARRAY SHAPE**

In [17]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [18]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


**NUMPY ARRAY RESHAPE**

In [22]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])           #4*3=12
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])           
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [30]:
arr=np.array([1,2,3,4,5,6])           
newarr=arr.reshape(2,3,1)
print(newarr)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [37]:
# arr=np.array([1,2,3,4,5,6,7,8])           
# newarr=arr.reshape(3,3)
# print(newarr)

#ValueError: cannot reshape array of size 8 into shape (3,3)

In [32]:
arr=np.array([1,2,3,4,5,6,7,8,9])           
newarr=arr.reshape(3,3)
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
arr=np.array([1,2,3,4,5,6,7,8])           
newarr=arr.reshape(2,1,-1)
print(newarr)

#note:we can not pass -1 to more than one dimention

[[[1 2 3 4]]

 [[5 6 7 8]]]
