**ARRAY CREATION**

In [1]:
import numpy


In [2]:
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
import numpy as np

In [6]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [7]:
print(np.__version__)

1.26.4


In [8]:
a=np.array((11,22,33,44))
print(a)

[11 22 33 44]


In [9]:
#0-D array
arr=np.array(24)
print(arr)

24


In [13]:
# 1-D array

arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [14]:
# 2-D array

arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [17]:
#3-D array

arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


**CHECK NO OF DIMESTIONS**

In [18]:
print(arr.ndim)

3


In [19]:
a=np.array(42)

print(a.ndim)

0


In [20]:
arr=np.array([1,2,3,4,5])
print(arr.ndim)

1


**HIGHER DIMENTIONAL ARRAY**

In [23]:
a=np.array([1,2,3,4],ndmin=3)
print(a)
print("Dimention:",a.ndim)

[[[1 2 3 4]]]
Dimention: 3


**CHANGE THE DATATYPE**

In [24]:
arr=np.array([1,2,3,4],dtype=complex)
print(arr)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [25]:
arr=np.array([1,2,3,4],dtype=float)
print(arr)

[1. 2. 3. 4.]


**NUMPY ARRAY SIZE AND SHAPE**

In [26]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("Shape of array is:",arr.shape)

Shape of array is: (2, 4)


In [27]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("Shape of array is:",arr.size)

Shape of array is: 8


**NUMPY ARRAY INDEXING**

In [29]:
arr=np.array([1,2,3,4])
print(arr[0])

1


In [30]:
print(arr[3])


4


In [31]:
print(arr[2]+arr[3])

7


**ACCESS 2-D ARRAY**

In [32]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,1])

2


In [33]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,1])

6


**ACCESS 3-D ARRAY**

In [35]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr[0,1,2])

6


**CREATING A SEQUENCE OF INTEGER USING ARANGE()**

In [36]:
arr=np.arange(11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [38]:
arr=np.arange(0,20,3)
print("A sequence array with step of 3 :\n",arr)

A sequence array with step of 3 :
 [ 0  3  6  9 12 15 18]


In [39]:
arr=np.arange(11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [40]:
print(arr[2])

2


In [41]:
print(arr[-2])

9


In [43]:
print(len(arr)-2)

9


In [44]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [45]:
print(arr.shape)

(2, 4)


In [47]:
print(arr[1,3])

8
